language: java

jdk:
  - oraclejdk7
  - oraclejdk8

branches:
  except:
    - gh-pages

cache:
  directories:
    - $HOME/.m2

script: mvn clean install -X
env: MAVEN_OPTS="-Xmx2G -XX:MaxPermSize=256m"